apiVersion: apps.taskapp.io/v1alpha1
kind: Backend
metadata:
  name: personal-backend
  labels:
    app.kubernetes.io/name: personal-backend
    app.kubernetes.io/managed-by: taskapp-operator
spec:
  image: boicotaz/taskapp-backend
  tag: latest
  replicas: 1
  dbSecret: taskapp-database-secret
  database:
    dbName: taskapp
    size: small
#  queue:
#    type: standard
#    deadLetter: false
    # urlEnvVar: SQS_QUEUE_URL   # optional — override the env var name injected into the container
