apiVersion: apps.taskapp.io/v1alpha1
kind: Backend
metadata:
  name: taskapp
  labels:
    app.kubernetes.io/name: taskapp
    app.kubernetes.io/managed-by: taskapp-operator
spec:
  image: boicotaz/taskapp-backend
  tag: latest
  replicas: 1
  database:
    dbName: taskapp
    size: small
    schema:
      sql: |
        CREATE TABLE IF NOT EXISTS tasks (
          id          SERIAL PRIMARY KEY,
          title       VARCHAR(255),
          description TEXT,
          status      VARCHAR(50),
          created_at  TIMESTAMP DEFAULT NOW()
        );
#  queue:
#    type: standard
#    deadLetter: false
#    urlEnvVar: SQS_QUEUE_URL
